### ISSUE TITLE
Wallet balance not reflected on other game pages 

### ISSUE THREAD

**Issue by santhoshsoundar** [besoeasy/onefastway#5]
<img width="1501" alt="Screen Shot 2020-05-10 at 5 57 28 PM" src="https://user-images.githubusercontent.com/14152628/81515309-3c4d7a80-92e8-11ea-8123-003ad3044c1d.png">
<img width="1503" alt="Screen Shot 2020-05-10 at 5 59 57 PM" src="https://user-images.githubusercontent.com/14152628/81515311-3e173e00-92e8-11ea-9b63-181028816dee.png">

**Comment by codeword7** [comment]
Hello, santhoshsoundar you have deposited to wallet, there is a button "Deposit To Casino" where you input the desire amount to transfer or you can click "MAX Deposit" where all your wallet funds will be transferred to CASINO. Casino balance is reflected on our each game not Wallet balance.
Thank you

**Comment by besoeasy** [comment]
exactly wallet balance & casino balance are different !!
